import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>[VHS CLUB]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Hero heading='VHS - CLUB' message='Sharing and documenting the golden age of film' button='Subscribe' />
    </div>
  )
}
